Here’s the complete and corrected settings.py code for your Django project:

"""
Django settings for linear_programming_solver project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# ----------------------------------------------
# 🔹 BASE DIRECTORY SETUP
# ----------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# ----------------------------------------------
# 🔹 SECURITY SETTINGS
# ----------------------------------------------
SECRET_KEY = 'django-insecure-!385^u&@%36!%9q4wq6oxpf^6d^4l@+33gfq2yv)3h246zoj^m'
DEBUG = True
ALLOWED_HOSTS = ['Linear_Programing.onrender.com', '127.0.0.1']

# ----------------------------------------------
# 🔹 MEDIA CONFIGURATION
# ----------------------------------------------
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ----------------------------------------------
# 🔹 APPLICATIONS INSTALLED
# ----------------------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'lp_solver',  # Custom app
]

# ----------------------------------------------
# 🔹 MIDDLEWARE CONFIGURATION
# ----------------------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ----------------------------------------------
# 🔹 URL CONFIGURATION
# ----------------------------------------------
ROOT_URLCONF = 'linear_programming_solver.urls'

# ----------------------------------------------
# 🔹 TEMPLATE CONFIGURATION
# ----------------------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # Global templates folder
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# ----------------------------------------------
# 🔹 WSGI APPLICATION
# ----------------------------------------------
WSGI_APPLICATION = 'linear_programming_solver.wsgi.application'

# ----------------------------------------------
# 🔹 DATABASE CONFIGURATION
# ----------------------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ----------------------------------------------
# 🔹 PASSWORD VALIDATION
# ----------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ----------------------------------------------
# 🔹 INTERNATIONALIZATION
# ----------------------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ----------------------------------------------
# 🔹 STATIC FILES CONFIGURATION
# ----------------------------------------------
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# ----------------------------------------------
# 🔹 MEDIA FILES CONFIGURATION
# ----------------------------------------------
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ----------------------------------------------
# 🔹 DEFAULT AUTO FIELD
# ----------------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
